HOME画面とポイント入力画面作成
liskis/tennisData5 pull request #1
Opened 2024-01-03 04:09 UTC by liskis

とりあえずcocoaPodsをインストールせずにViewから作成しました。
TennisData5Appが読み込まれると
View.ContentViewが読み込まれます。
ContentViewにはTabViewが設定されていて、
HomeVIew,MatchRecordView,DataAnalysisViewを切り替えます。
HomeViewからGameStartBtnsAreaのbuttonをクリックすると、
gameTypeパラメータを持ってMatchViewに遷移します。
Realmからのデータのやり取りは、各ViewのControllerクラスを作って制御する予定です。

2024-01-04 09:47 UTC, LunaChevalier requested changes
ディレクトリの構成から見ると、MVCアーキテクチャを採用しているかと思いますが、どういったアーキテクチャを採用したのかをプルリクエストの概要に記載してください

また、処理の流れではなく、システム仕様書のどの機能、どの画面を実装したのかを記載してください
[基本的な書き方とフォーマットの構文](https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)を活用して、以下のテンプレで記載するようお願いします

```
## 概要
<!-- 今回実装した機能や画面を1行で説明する -->

## やったこと
<!--
今回実装した機能や画面を箇条書きでリストアップする
できるだけシステム仕様書と文言が一致する様に記載する
-->

## レビュー観点
<!--
どういった観点でレビューしてほしいのか、特筆すべきことがあれば記載お願いします
(例)
☓☓の方針で実装したが、これがプログラムにちゃんと反映されているか?
〇〇の使い方はあっているのか?
△△の部分は一時的に実装したので、そこまで重点的にレビューしなくて良い
など
-->

## スクリーンショット
<!--
画面を実装した場合、最終的に完成した画面を載せてもらえると助かります
内部処理の見直しなど、見た目上出てこないものに関しては不要です
-->

```

また、次回からのプルリクエストで良いので、画面単位、機能単位でリクエストを行うようにお願いします
今回だと、HOME画面の見た目実装完了でプルリクエスト、ポイント入力画面の見た目実装完了でプルリクエスト、合計2つのプルリクエストが出来るようなイメージになります

2024-01-04 09:47 UTC, LunaChevalier commented on TennisData5/Controller/HomeController.swift
> +    static let firstServIn: [HomeGraphData] = [
Controllerクラスは、画面からの入力に対してどういった処理を行うかを実装します
例えば、登録ボタンを押した時、登録に必要なデータをViewからもらって、Controller内でRealmの登録を行う処理をこのクラスで実装します
現在実装しているのは、データの構造だとなので、こういったものはModelクラスやRepositoryクラス(データの管理を行うクラス)に実装してください

2024-01-04 09:47 UTC, LunaChevalier commented on TennisData5/Controller/HomeController.swift
> +    static let firstServIn: [HomeGraphData] = [
また、`static`はアプリ全体を通してデータが変わらないものにだけつけるので、こういった登録したデータによって値が変わってしまうものにつけるのはNGです

2024-01-05 08:55 UTC, LunaChevalier requested changes
データ構造がまだControllerに残っていたので、Modelの方に移植をお願いします

2024-01-05 08:55 UTC, LunaChevalier commented on TennisData5/Controller/PointInputController.swift
> +    let userName:String = "わたなべ"
データの構造がControllerに残っているので、Modelの方に移植してください

2024-01-05 08:55 UTC, LunaChevalier commented on TennisData5/Controller/HomeController.swift
> +    let firstServIn: [HomeGraphData] = [
データの構造がControllerに残っているので、Modelの方に移植してください

2024-01-05 09:48 UTC, liskis commented on TennisData5/Controller/PointInputController.swift
> +    let userName:String = "わたなべ"
let userName:String = "わたなべ"
    let partnerName:String = "partner"
    let opponentName:String = "対戦相手"
    let opponentsName:String = "対戦チーム"
    let winCount:Int = 3
    let loseCount:Int = 2
    let myPoint:Int = 2
    let opponentPoint:Int = 1
    let inputModeText:String = "アドバンスモード"
は、Realmからのデータで算出するものなので、
データ構造ではないです。

2024-01-06 14:17 UTC, liskis commented on TennisData5/Controller/HomeController.swift
> +    let firstServIn: [HomeGraphData] = [
意味がわかりません

2024-01-08 11:39 UTC, merged